version: "3"

services:

  #Aplicação
  app:
    build: 
      context: ./
      dockerfile: ./docker/app.dockerfile
    container_name: app-petshop
    volumes:
      - ${APP_PATH}:/var/www
    networks: 
      - frontend
      - database
  
  #Banco de Dados
  database:
    image: postgres:9.5-alpine
    container_name: db-petshop
    # build: 
    #   context: ./
    #   dockerfile: ./docker/db.dockerfile
    volumes:
        - "dbdata:${DB_DATA}"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "5432:${DB_PORT}"
    networks:
      - database
      
  #Servidor Web
  web:
    image: nginx:1.10
    build:
      context: ./
      dockerfile: ./docker/web.dockerfile
    container_name: web-petshop
    volumes:
      - ./app:/var/www
      - ./settings/web/app.conf:/etc/nginx/conf.d/default.conf
      - ./settings/web/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:${WEB_PORT}
    networks: 
      - frontend

volumes:
  dbdata:

networks:
  frontend:
    driver: bridge
  database:
    driver: bridge